name: coc_character
description: "克苏鲁的呼唤 第七版 角色卡应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  pdf: ^3.10.0
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/character.jpg
    - assets/d20.png
    - assets/1920sCha_01.png
    - assets/1920sCha_02.png
